### ISSUE TITLE
Сопровождающие фразы

### ISSUE THREAD

**Issue by toivopr** [anindrikson/puzzle_game_01#11]

**Comment by toivopr** [comment]
- 499 people died in this room before you. You will definitely succeed
- Welcome to your interview at Tie Industries, please go to the testing room to start the test.
- Imagine that every step taken across this bridge would cost the company one million dollars. As an experienced manager, what will you do if you need to cross to the other side of the bridge?
- If you will open one door, out came a hungry tiger. The tiger immediately jumps on you and tear you to pieces.
But, if the accused opened the other door, there came forth from it a woman, chosen especially for you. 
 Be careful with the choice
- What part of your body are you willing to give up to open this door?

**Comment by MaxMeetGit** [comment]
До этого этапа доходит менее половины ректутируемых, сейчас нам важно знать как наш будущий сотрудник на высокой должности, будет вести себя в агрессивной среде(уровень с кислотой)
Номер 11 367, теперь вы подаёте пример другим участникам, что для процветания компании надо иногда жертвовать собой, во благо других (обязательная смерть у куба с лазерами)
Что вы будете делать, если у вас мало ресурсов, а обстоятельства требуют комплексного решения, покажите нам, пожалуйста (комната с кубом и двумя кнопками)
Поздравляем, вы - тот кто нам подходит, пожалуйста, встаньте на кнопку и получите наивысшую награду - респектабельную работу в нашей компании, поздравляем... сотрудник. (финал в комнате с галстуком)

**Comment by MaxMeetGit** [comment]
Но не забывайте, что  вы нам нужны, пока вы полезны для нас, и незаменимых людей нет (финал)

**Comment by toivopr** [comment]
> До этого этапа доходит менее половины ректутируемых, сейчас нам важно знать как наш будущий сотрудник на высокой должности, будет вести себя в агрессивной среде(уровень с кислотой)
> Номер 11 367, теперь вы подаёте пример другим участникам, что для процветания компании надо иногда жертвовать собой, во благо других (обязательная смерть у куба с лазерами)
> Что вы будете делать, если у вас мало ресурсов, а обстоятельства требуют комплексного решения, покажите нам, пожалуйста (комната с кубом и двумя кнопками)
> Поздравляем, вы - тот кто нам подходит, пожалуйста, встаньте на кнопку и получите наивысшую награду - респектабельную работу в нашей компании, поздравляем... сотрудник. (финал в комнате с галстуком)

- Less than half of the candidates reach this stage - good work. This test will show how our future employees will behave in an aggressive environment.
- Number 11 367, you are an example for the other participants. Indeed, for the prosperity of a company,  sometimes it is necessary to sacrifice oneself, for the benefit of others
- please show us what you will do if you are short on resources, but the situation requires a comprehensive solution.
- Congratulations, you are the one we need, click on the button, and get the highest award - a decent job in our company, congratulations ... employee.

**Comment by toivopr** [comment]
> Но не забывайте, что вы нам нужны, пока вы полезны для нас, и незаменимых людей нет (финал)

- But don't forget that we need you while you are useful to us. there are no irreplaceable people

**Comment by MaxMeetGit** [comment]
Поздравляем, вы - тот кто нам подходит, пожалуйста, подойдите и получите наивысшую награду - респектабельную работу в нашей компании, поздравляем... сотрудник. (финал в комнате с галстуком)

**Comment by anindrikson** [comment]
При входе в комнату с кучей смертоносных ловушек:
Tie industries prides itself as the company which exercises diversity and inclusion as one of its' core values. All candidates are equal in their right to enter these test chambers and compete for a chance to earn the crimson tie.

**Comment by anindrikson** [comment]
Предлагаю небольшое исправление. В первой комнате голос говорит "499 people died in this room before you". 
Мне кажется, истинный корпоративный крысич никогда ничего не станет говорить открытым текстом и упоминать смерть испытуемых.
Предлагаемое изменение: 499 people failed to pass this test chamber. However, we believe that you, candidate name, possess unique qualities to face this challenge.

**Comment by anindrikson** [comment]
При входе в комнату с кубом-пидором: Thinking outside the box is one of the company's core values. However, due to recent events, this core value no longer applies to medics, porters and emergency technicians.
